### ISSUE TITLE
Epic - SQL Managed Instance

### ISSUE THREAD

**Issue by iriahk89** [aztfmod/terraform-azurerm-caf#106]
# mssql_mi
- [x] sqlmi module based on arm deployment (create, update)
- [x] example (subnet prereq: service delegation, NSG, Routes)
- [x] destroy part (sqlmi, Virtual Cluster)
- [x] Administrators
- [x] Failover Groups
- [x] Encryption Protector & Keys #204 
- [ ] Restorable Dropped Databases
- [ ] Security Alert Policies
- [ ] Vulnerability Assessments
- [ ] Instance Pool
- [ ] Server Trust Groups
- [ ] Restore MI from another MI backup

# managed db
- [x] managed database (brand new db: Default)
- [x] managed database (PointInTimeRestore)
- [ ] managed database (RestoreExternalBackup)
- [ ] managed database (Recovery)
- [x] managed database (RestoreLongTermRetentionBackup) #184
- [x] Backup Short Term Retention Policies
- [x] Backup Long Term Retention Policies #184
- [ ] Security Alert Policies
- [ ] Vulnerability Assessments

**Comment by arnaudlh** [comment]
Closing in favor or the native TF provider.
