### ISSUE TITLE
Epic - Application Gateway

### ISSUE THREAD

**Issue by LaurentLesle** [aztfmod/terraform-azurerm-caf#118]
# azurerm_application_gateway
- [x] create one or multiple agw (create, update)
- [x] example (subnet prereq: service delegation, NSG, Routes)
- [x] Add diagnostics settings
- [ ] Set the TLS protocol version
- [x] Set the SSL policy name
- [ ] Add authentication certificates
- [x] Add trusted root certificates
- [x] Add WAF configuration
- [ ] Add Auto scale configuration
- [x] Add Custom error configuration

# applications
- [x] create one or multiple applications to expose in the agw
- [x] expose the application through multiple listeners (private and or public)
- [x] Integrate with Keyvault self-signed certificate for HTTPs
- [x] Integrate with Keyvault existing certificate from file
- [x] Integrate with Keyvault existing certificate from Keyvault secret (certificate base64 in secret's value)
- [x] Integrate with Keyvault and external certificate provider
- [x] Add custom probes
- [x] Add URL path map
- [x] Add Rewrite rule set

**Comment by arnaudlh** [comment]
Closing the issue as the features have been implemented.
