### ISSUE TITLE
Epic - Onboarding materials

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/terraform-azurerm-caf#15]
## Videos

- [x] Setup dev environment
- [ ] Identity bootstrap
- [ ] Zoom: launchpad light
- [ ] Zoom: launchpad standard
- [ ] Zoom: networking 
- [ ] Zoom: foundations
- [ ] Development 101

## Guidance
- [ ] Setup dev environment (local and VScode)
- [ ] Identity bootstrap
- [ ] Deployment guide
- [ ] Customisation guide
- [ ] Development guide

**Comment by arnaudlh** [comment]
Closing as will add wiki and CAF doc update
