### ISSUE TITLE
Epic - Private Endpoint

### ISSUE THREAD

**Issue by LaurentLesle** [aztfmod/terraform-azurerm-caf#159]
- [ ]  Add private DNS to private endpoint

Add support for the following services
- [x] Azure SQL Database
- [ ] Azure Automation
- [x] Azure Storage
- [x] Azure Data Lake Storage Gen2
- [ ] Azure Cosmos DB
- [x] Azure Database for PostgreSQL [#148]
- [x] Azure Database for MySQL [#155]
- [x] Azure Database for MariaDB [#161]
- [ ] Azure IoT Hub
- [x] Azure Key Vault
- [ ] Azure Kubernetes Service - Kubernetes API
- [ ] Azure Search
- [x] Azure Container Registry
- [ ] Azure App Configuration
- [x] Azure Backup [#178]
- [x] Azure Event Hub [#178]
- [ ] Azure Service Bus
- [ ] Azure Relay
- [ ] Azure Event Grid
- [ ] Azure App Service
- [ ] Azure Machine Learning
- [ ] SignalR
- [ ] Azure Monitor
- [ ] Cognitive Services
- [ ] Azure File Sync
- [x] Azure Recovery Vault Service
