### ISSUE TITLE
Epic - Networking features addition

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/terraform-azurerm-caf#2]
Adding networking features:

# Virtual WAN
- [x] Add support for Virtual WAN and Virtual Hubs 
- [x] Add support for Virtual WAN and Virtual Hubs Firewall Manager
- [x] Add support for Virtual WAN and Virtual Hubs routes
- [ ] P2S: Add support for additional AuthN methods
- [ ] P2S : Add support for certificate generation and storage in AKV
- [x] Add support for Virtual Hubs peering with Azure Virtual Networks
- [x] Add example for hub spoke model using Virtual WAN and Vnets

# Filtering
- [x] Add support for Azure Firewall NAT rule collection 
- [x] Add support for DDoS Standard
- [ ] Add support for Network Watcher & Traffic Analytics

# Core 
- [x] Add support for naming convention provider 1.0
https://github.com/aztfmod/terraform-provider-azurecaf/blob/master/docs/resources/azurecaf_name.md
- [x] General module refactoring
