### ISSUE TITLE
January 2021 Features plan

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/terraform-azurerm-caf#206]
## Rover
- [x] Add initial support for TFC/TFE as remote backend - https://github.com/aztfmod/rover/pull/101
- [x] Detecting "owner" privileges on subscription for launchpad - https://github.com/aztfmod/rover/issues/13
- [x] Adding Kubectl autocomplete - https://github.com/aztfmod/rover/issues/88
- [x] Preserve bash history - https://github.com/aztfmod/rover/issues/100
- [x] Add sqlcmd command line tool
	
## Modules
- [x] All modules available as standalone [#222]
- [x] All modules with examples [#222]
- [x] All modules with documentation and documentation automation [#220]
- [x] Update to Azure Kubernetes Support [#230]

#### Additions: 
- [x] Add support for password rotation for Azure AD apps and users [#237]
- [x] Azure NetApp [#235 ]
- [x] Azure Front Door [#234]
- [x] KeyVault Certificate Issuer [#234]
- [x] Azure App Service DNS zone [#234]
- [x] Azure Domain Names registration [#234]
- [x] FrontDoor [#151]
- [x] mySQL [#61]
- [x] PostgreSQL[#61]
- [x] MariaDB [#158]
- [x] SQL MI LTR Backup [#184]
- [x] SQL MI BYOK [#204]
- [x] Add PrivateLink for MSSQL Servers [#209 ]
- [X] Cosmos DB support for Gremlin, Cassandra, Tables [#218] [#217] [#214]
	
## Starter
- [ ] DevOps platform and agents for Azure DevOps
	
## Landing zones		
- [x] Introducing solutions: App Service Environment in main repo https://github.com/Azure/caf-terraform-landingzones/issues/126
- [x] Introducing solutions: MLOps (data and analytics) in main repo https://github.com/Azure/caf-terraform-landingzones/issues/126
- [x] Introducing solutions: AKS in main repo https://github.com/Azure/caf-terraform-landingzones/issues/126
