### ISSUE TITLE
February 2021 Features plan 

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/terraform-azurerm-caf#232]
## Core
- [ ] Upgrade to Terraform 14.X  (https://github.com/aztfmod/terraform-azurerm-caf/issues/250) (ready but moved to March) 
- [ ] CAF variables in resource tags - https://github.com/aztfmod/rover/issues/99 (moved to March) 

## Rover
- [x] CentOs container replacement: Ubuntu  (https://github.com/aztfmod/rover/issues/107)

#### Additions: 
- [ ] Virtual Desktop Workspace (https://github.com/aztfmod/terraform-azurerm-caf/issues/212)
- [x] Eventhub and namespaces (#203 #200)
- [ ] Stream Analytics (https://github.com/aztfmod/terraform-azurerm-caf/issues/97)
- [ ] LogicApp (https://github.com/aztfmod/terraform-azurerm-caf/issues/253)
- [ ] Functions  (https://github.com/aztfmod/terraform-azurerm-caf/issues/251)
- [ ] Data Factory (https://github.com/aztfmod/terraform-azurerm-caf/issues/95)
- [ ] APIM [#205]
- [ ] Security Center Continuous Export [#181]
- [x] App Gateway: URL Rewrite (https://github.com/aztfmod/terraform-azurerm-caf/issues/118)
- [x] Load balancer (https://github.com/aztfmod/terraform-azurerm-caf/issues/247)

## Starter
- [ ] Advanced DevOps pipelines and agents for Azure DevOps  (https://github.com/Azure/caf-terraform-landingzones-starter/issues/20)
- [x] ES: Contoso reference architecture (https://github.com/Azure/caf-terraform-landingzones-starter/issues/21)
- [ ] ES: Adventure works reference architecture (https://github.com/Azure/caf-terraform-landingzones-starter/issues/22)
- [ ] ES: Wingtip reference architecture	(https://github.com/Azure/caf-terraform-landingzones-starter/issues/23)	
- [x] AKS Construction Set Iteration (https://github.com/Azure/caf-terraform-landingzones-starter/issues/24)
- [ ] Improve documentation for cross subscription composition. (https://github.com/Azure/caf-terraform-landingzones-starter/issues/25)

## Landing zones
- [ ] ESLZ: ES Diagnostics policy integration (https://github.com/Azure/caf-terraform-landingzones/issues/131)	
- [x] Deprecate old MLOps, AKS, repositories in AZTFMOD (as merged into CAF main repo as caf_solution) (https://github.com/Azure/caf-terraform-landingzones/issues/132)
