### ISSUE TITLE
March 2021 Features plan

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/terraform-azurerm-caf#311]
## Core
- [x] Upgrade to Terraform 14.X  (https://github.com/aztfmod/terraform-azurerm-caf/issues/250)
- [ ] CAF variables in resource tags - https://github.com/aztfmod/rover/issues/99
#### Additions: 
- [ ] Virtual Desktop Workspace (https://github.com/aztfmod/terraform-azurerm-caf/issues/212)
- [x] Eventhub and namespaces (#203 #200)
- [x] Shared Image Gallery (https://github.com/aztfmod/terraform-azurerm-caf/pull/326 https://github.com/aztfmod/terraform-azurerm-caf/issues/52)
- [x] Adding LogicApp, Function, Data Factory  [#319]
- [x] Adding NSG module with NIC association [#333]
- [x] Enhance sqldb module to create db user for managed identity [#339]
- [x] Subscriptions Vending Machine [#328 ]
- [X] Application Security Groups
