### ISSUE TITLE
Epic - mssql_database

### ISSUE THREAD

**Issue by LaurentLesle** [aztfmod/terraform-azurerm-caf#32]
# mssql Database
- [x] Add database to existing sql server - 
- [x] Add database to remote sql server -
- [x] Add Azure AD authentication for user and groups - https://docs.microsoft.com/en-us/azure/azure-sql/database/secure-database-tutorial#azure-ad-authentication

**Comment by arnaudlh** [comment]
Closing as all work items completed within https://github.com/aztfmod/terraform-azurerm-caf/releases/tag/5.3.0
