### ISSUE TITLE
Epic - Compute Windows/Linux Virtual Machine features

### ISSUE THREAD

**Issue by LaurentLesle** [aztfmod/terraform-azurerm-caf#4]
# Linux Virtual Machine
- [x] Add support to create a VM from image reference
- [x] Add support to create VM from image gallery [#463]
- [x] Add support to assigned System Managed Identity 
- [x] Add support to assign one or multiple User Managed Identity
- [x] Add support to assign one or multiple User Managed Identity recreated in a different tfstate
- [x] Add support to create and attach one or multiple nics. Nics can connect to a local or remote vnet/subnet
- [x] Generate ssh public / private keys if not specified and store them into keyvault secret
- [x] Add support to boot diagnostics
- [x] Add support to dedicated host
- [x] Add support for availability set [#143 ]
- [x] Add support for proximity placement group [#145]
- [x] Add support for vm scale set [#348]
- [x] Add support for ultra ssd
- [x] Insert multiple certificates from keyvault
- [x] Insert public key for Linux virtual machine from AKV
- [x] Insert password for Windows virtual machine from AKV
- [x] Support for VM backup configuration [#128]
- [x] Support for VM extension setup [#131] 
- [x] Attach multiple data disks
- [x] Add write acceleration to os disk
- [x] Add support for VM remote configuration (Ansible, remote execution, etc.) [#439]

**Comment by arnaudlh** [comment]
Closing the epic in favor of the feature issues.
