### ISSUE TITLE
Epic - VM Extensions Support

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/terraform-azurerm-caf#514]
VM Extensions support:
- [x] Cloud Monitoring
- [x] Log Analytics Agent
- [x] AD Domain Join
- [x] DSC Extension for Azure Virtual Desktop
- [x] Custom Script Extension
- [x] SQL Extension - https://github.com/aztfmod/terraform-azurerm-caf/issues/646 

VMSS Extensions support:
- [x] AD Domain Join
- [x] Custom Script Extension

Proposed additions:
- [ ] Network Watcher [#340]
- [ ] App Insights [#285]
- [ ] Azure Monitor (preview) - [Instructions](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-install?tabs=ARMAgentPowerShell%2CPowerShellWindows%2CPowerShellWindowsArc%2CCLIWindows%2CCLIWindowsArc)

**Comment by RobAshton-IM** [comment]
Hi Arnaud, are there any immediate plans for developing support for the SqlVirtualMachine resource type? (I believe that's the correct underlying AzureRM resource type for the "SQL Extension" above)

It should correlate to the [Terraform Registry: Azure RM - MSSQL Virtual Machine](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_virtual_machine) resource.

I'm working on a project that will be migrating such objects from a manually-created landing zone to one built entirely with the CAF for Terraform supermodule over the next few weeks, so would ideally like to get or add that support if possible.

**Comment by arnaudlh** [comment]
hi @RobAshton-IM - tagging was not done correctly :) the capability is in the module as per this: https://github.com/aztfmod/terraform-azurerm-caf/issues/646 and you can find an example here: https://github.com/aztfmod/terraform-azurerm-caf/blob/ef75c2783e83625027d6eb6e6af66dfef7958cb4/examples/compute/virtual_machine/108-mssql-vm/configuration.tfvars  let us know if that works for you!

**Comment by RobAshton-IM** [comment]
Many thanks Arnaud, I'd not spotted that's where it lives :)
