### ISSUE TITLE
Epic: API Management

### ISSUE THREAD

**Issue by willis7** [aztfmod/terraform-azurerm-caf#644]
Having looked at the modules root and network subdirectory it appears there is no CAF implementation for [API Management](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management).

Judging by the huge list below it looks like this is no mean feat. As we need this in my organisation I will attempt to follow @arnaudlh [guide](https://www.arnaudlheureux.io/2021/06/22/writing-your-first-contribution-to-caf-terraform-module/). This looks like a hard first contribution, so I would be prepared for lots of questions 😅.

Do you have any recommendations on how to break down the PR's? Is per-resource a good option here?

API Management

-   Resources
    
    - [ ]   [azurerm\_api\_management](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management)    
    - [ ]   [azurerm\_api\_management\_api](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api)    
    - [ ]   [azurerm\_api\_management\_api\_diagnostic](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api_diagnostic)    
    - [ ]   [azurerm\_api\_management\_api\_operation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api_operation)    
    - [ ]   [azurerm\_api\_management\_api\_operation\_policy](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api_operation_policy)    
    - [ ]   [azurerm\_api\_management\_api\_operation\_tag](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api_operation_tag)    
    - [ ]   [azurerm\_api\_management\_api\_policy](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api_policy)    
    - [ ]   [azurerm\_api\_management\_api\_release](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api_release)    
    - [ ]   [azurerm\_api\_management\_api\_schema](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api_schema)    
    - [ ]   [azurerm\_api\_management\_api\_version\_set](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api_version_set)    
    - [ ]   [azurerm\_api\_management\_authorization\_server](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_authorization_server)    
    - [ ]   [azurerm\_api\_management\_backend](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_backend)    
    - [ ]   [azurerm\_api\_management\_certificate](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_certificate)    
    - [ ]   [azurerm\_api\_management\_custom\_domain](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_custom_domain)    
    - [ ]   [azurerm\_api\_management\_diagnostic](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_diagnostic)    
    - [ ]   [azurerm\_api\_management\_email\_template](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_email_template)    
    - [ ]   [azurerm\_api\_management\_gateway](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_gateway)    
    - [ ]   [azurerm\_api\_management\_gateway\_api](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_gateway_api)    
    - [ ]   [azurerm\_api\_management\_group](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_group)    
    - [ ]   [azurerm\_api\_management\_group\_user](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_group_user)    
    - [ ]   [azurerm\_api\_management\_identity\_provider\_aad](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_identity_provider_aad)    
    - [ ]   [azurerm\_api\_management\_identity\_provider\_aadb2c](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_identity_provider_aadb2c)    
    - [ ]   [azurerm\_api\_management\_identity\_provider\_facebook](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_identity_provider_facebook)    
    - [ ]   [azurerm\_api\_management\_identity\_provider\_google](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_identity_provider_google)    
    - [ ]   [azurerm\_api\_management\_identity\_provider\_microsoft](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_identity_provider_microsoft)    
    - [ ]   [azurerm\_api\_management\_identity\_provider\_twitter](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_identity_provider_twitter)    
    - [ ]   [azurerm\_api\_management\_logger](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_logger)    
    - [ ]   [azurerm\_api\_management\_named\_value](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_named_value)    
    - [ ]   [azurerm\_api\_management\_openid\_connect\_provider](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_openid_connect_provider)    
    - [ ]   [azurerm\_api\_management\_policy](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_policy)    
    - [ ]   [azurerm\_api\_management\_product](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_product)    
    - [ ]   [azurerm\_api\_management\_product\_api](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_product_api)    
    - [ ]   [azurerm\_api\_management\_product\_group](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_product_group)    
    - [ ]   [azurerm\_api\_management\_product\_policy](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_product_policy)    
    - [ ]   [azurerm\_api\_management\_property](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_property)    
    - [ ]   [azurerm\_api\_management\_redis\_cache](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_redis_cache)    
    - [ ]   [azurerm\_api\_management\_subscription](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_subscription)    
    - [ ]   [azurerm\_api\_management\_tag](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_tag)    
    - [ ]   [azurerm\_api\_management\_user](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_user)    

-   Data Sources
    
    - [ ]  [azurerm\_api\_management](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/api_management)    
    - [ ]  [azurerm\_api\_management\_api](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/api_management_api)    
    - [ ]  [azurerm\_api\_management\_api\_version\_set](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/api_management_api_version_set)    
    - [ ]  [azurerm\_api\_management\_gateway](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/api_management_gateway)    
    - [ ]  [azurerm\_api\_management\_group](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/api_management_group)    
    - [ ]  [azurerm\_api\_management\_product](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/api_management_product)    
    - [ ]  [azurerm\_api\_management\_user](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/api_management_user)

**Comment by arnaudlh** [comment]
hi @willis7 there were some attempt couple of weeks ago by @hieumoscow and his work is on https://github.com/aztfmod/terraform-azurerm-caf/tree/HN-apim maybe there are some things to reuse there? :)

**Comment by willis7** [comment]
We're at a similar level however I have placed my module under _networking_ as opposed to _compute_. Do you have a recommendation here?

**Comment by arnaudlh** [comment]
i would say its compute but Im open to debates :)

**Comment by willis7** [comment]
Apologies, unfortunately, APIM was pulled from our solution so it looks like I won't have the time to contribute to this.

**Comment by abdulrabbani00** [comment]
Hello,

I have added the API management module: https://github.com/aztfmod/terraform-azurerm-caf/pull/719

I have tested the creation with a few parameters and it works. A few points:
1. This only contains the azurerm_api_management module.
2. I placed the module under a new `api_management_services` folder. Let me know if this doesn't work.

@hriaz will be doing further testing before the PR is ready for review.

**Comment by nusrath432** [comment]
I'll be adding the following:

Phase 1:
 azurerm_api_management_product
 azurerm_api_management_product_api
 azurerm_api_management_product_group
 azurerm_api_management_product_policy
 
 Phase2:
 azurerm_api_management_api
 azurerm_api_management_api_diagnostic
 azurerm_api_management_api_operation
 azurerm_api_management_api_operation_policy
 azurerm_api_management_api_operation_tag
 azurerm_api_management_api_policy
 azurerm_api_management_api_release
 azurerm_api_management_api_schema
 azurerm_api_management_api_version_set
 
 Would be good to know a common branch so that we could avoid duplication.
