### ISSUE TITLE
Epic: Hashicorp Terraform Cloud Support

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/terraform-azurerm-caf#9]
Support for Terraform Cloud/Enterprise:

## Launchpad - support an add-on
- [x] Capability of bootstrapping the TFE/TFC environment 
- [x] Using an existing TFE/TFC environment given parameters
- [x] Create the workspace for the landing zones execution

## Core 
- [x] Manage landing zone service composition across levels transparently of the underlying backend (minimal code rewrite, feature flag to switch from azurerm, TFE, TFC, migration path would be nice)
 
Initial implementation: https://github.com/Azure/caf-terraform-landingzones/tree/0.4-tfc

**Comment by arnaudlh** [comment]
Initial support for TFC bootstrap as add-on: https://github.com/Azure/caf-terraform-landingzones/pull/92

**Comment by arnaudlh** [comment]
Now tracked as LZ addon - https://github.com/Azure/caf-terraform-landingzones/issues/96
